make install/uninstall POSIX-compliant

diff --git a/install b/install
--- a/install
+++ b/install
@@ -17,10 +17,12 @@
 # You should have received a copy of the GNU General Public License
 # along with smux; if not, see <http://www.gnu.org/licenses/>.
 
-next=0
+# POSIX
+set -o errexit
+set -o nounset
+
 verbose=0
 devel=0
-version=0.0.1
 
 # Print usage to stdout.
 # Arguments:
@@ -35,14 +37,13 @@ Options:
 	--prefix/-P:		base bath where all files will be deployed (default /usr/local if root, ~/.local if not)
   --devel/-d:   symlink to install location rather than copy, helpful for testing during development
                 ignored if not in the repository
-	--next/-N:		install latest development version from git, instead of the latest stable release.
 	--help/-h:		show this message
 	-v:			show more verbosity
 EOF
 }
 
 # Parse arguments
-while :; do
+while [ "$#" -gt 0 ]; do
 	case $1 in
 		-h | --help)
 			# Call a "show_help" function to display a synopsis, then exit.
@@ -57,12 +58,6 @@ while :; do
       shift
       devel=1
       ;;
-		-N | --next)
-			if [ -n "$2" ]; then
-				shift
-				next=1
-			fi
-			;;
 		-P | --prefix)
 			if [ -n "$2" ]; then
 				prefix="$2"
@@ -75,10 +70,15 @@ while :; do
 	esac
 done
 
+# set verbosity
+if [ "${verbose}" -ne 0 ]; then
+	set -o xtrace
+fi
+
 if  [ -z "${prefix}" ]; then
 	prefix="/usr/local"
 	# in case we're not root, just default to the home directory
-	if [ "$(id -u)" -ne 0 ]; then
+	if [ "$(id -u || true)" -ne 0 ]; then
 		prefix="${HOME}/.local"
 	fi
 fi
@@ -86,24 +86,15 @@ completion_dest_path="${prefix}/share/bash-completion/completions/"
 dest_path="${prefix}/bin"
 man_dest_path="${prefix}/share/man/man1"
 
-# POSIX
-set -o errexit
-set -o nounset
-# set verbosity
-if [ "${verbose}" -ne 0 ]; then
-	set -o xtrace
-fi
-
 # get current dir
 curr_dir=$(dirname "$0")
 cd "${curr_dir}" || exit 1
 
 # if files are available, install files in dest directory
-# else download targz and uncompress it
 if [ -e "${curr_dir}/smux" ]; then
   if [ "${devel}" -ne 0 ]; then
-    copy="ln -s -t"
-    if ! ${copy} "${dest_path}" "$(pwd)/smux"; then
+    copy="ln -sf -t"
+    if ! ${copy} "${dest_path}" "${PWD}/smux"; then
 	    printf >&2 "Do you have permission to write to %s?\n" "${dest_path}"
       exit 1
     fi
@@ -115,70 +106,32 @@ if [ -e "${curr_dir}/smux" ]; then
     fi
   fi
 	if [ -e "man" ]; then
-    for file in "$(pwd)"/man/man1/*; do
+    for file in "${PWD}"/man/man1/*; do
 		  ${copy} "${man_dest_path}" "${file}"
 		done
 	fi
 	if [ -e "completions" ]; then
-    for file in "$(pwd)"/completions/*; do
+    for file in "${PWD}"/completions/*; do
 			${copy} "${completion_dest_path}" "${file}"
 		done
 	fi
 else
-	printf >&2 "\033[1;31m Checking dependencies...\n\033[0m"
-	# check that we have base dependencies
-	if ! command -v wget > /dev/null || ! command -v tar > /dev/null; then
-		printf >&2 "Online install depends on tar wget\n"
-		printf >&2 "Ensure you have all dependencies installed.\n"
-		exit 1
-	fi
-
-	printf >&2 "\033[1;31m Downloading...\n\033[0m"
-	if [ "${next}" -eq 0 ]; then
-		release_ver="tomeichlersmith/smux/archive/refs/tags/${version}.tar.gz"
-		release_name=$(echo "${release_ver}" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+\.tar\.gz$')
-	else
-		release_ver="tomeichlersmith/smux/archive/refs/heads/main.tar.gz"
-		release_name="main"
-	fi
-	# go in tmp
-	tmp_dir="$(mktemp -d)"
-  if [ "${verbose}" -ne 0 ]; then
-    wget -O - "https://github.com/${release_ver}" |\
-      tar xzv --strip-components=1 --directory ${tmp_dir}
-  else
-    wget -q -O - "https://github.com/${release_ver}" |\
-      tar xz --strip-components=1 --directory ${tmp_dir}
-  fi
-	cd "${tmp_dir}"
-	# uncompress
-	printf >&2 "\033[1;31m Deploying...\n\033[0m"
-	# deploy our files
-  _unpack_root="smux-$(echo "${release_name}" | sed 's/.tar.gz//')"
-  if ! install -D -m 0755 -t "${dest_path}" "${_unpack_root}/smux"; then
-	  printf >&2 "Do you have permission to write to %s?\n" "${dest_path}"
-    exit 1
-  fi
-	if [ -e "${_unpack_root}/man/" ]; then
-		for file in "${_unpack_root}"/man/man1/*; do
-			install -D -m 0644 -t "${man_dest_path}" "${file}"
-		done
-	fi
-	if [ -e "${_unpack_root}/completions/" ]; then
-    for file in "${_unpack_root}"/completions/*; do
-			install -D -m 0644 -t "${completion_dest_path}" "${file}"
-		done
-	fi
-
-	# securely delete unneeded files
-	cd
-	if [ -n "${tmp_dir}" ] && [ -e "${tmp_dir}" ]; then
-		rm -rf "${tmp_dir}"
-	fi
+	printf >&2 "\033[1;31m Not inside code repository, cannot install smux\033[0m"
+  exit 1
 fi
 
 [ ! -w "${dest_path}" ] && printf >&2 "Cannot write into %s, permission denied.\n" "${dest_path}" && exit 1
 [ ! -w "${man_dest_path}" ] && printf >&2 "Cannot write into %s, permission denied.\n" "${man_dest_path}" && exit 1
 
 printf >&2 "\033[1;31m Successfully installed to %s.\n\033[0m" "${dest_path}"
-printf >&2 "\033[1;31m Be sure that %s is in your \$PATH environment variable for it to work.\n\033[0m" "${dest_path}"
+case "${PATH}" in
+  *"${dest_path}"*)
+    if [ "${verbose}" -ne 0 ]; then
+      printf >&2  "  Found %s in PATH\n" "${dest_path}"
+    fi
+    ;;
+  *)
+    printf >&2 "\033[1;31m Unable to find %s in PATH.\n\033[0m" "${dest_path}"
+    printf >&2 "\033[1;31m Be sure that %s is in your \$PATH environment variable for smux to work.\n\033[0m" "${dest_path}"
+    ;;
+esac
